### ISSUE TITLE
Data Lookup returning no results

### ISSUE THREAD

**Issue by JohnGalt1717** [hernantz/jSuggest#2]
I have a data source that is being passed "dea" and returnning a result

However I get the drop down showing me "no results"

The data is returning ID and Name properties in the array and the retrieveComplete is passing the single result from the data source.

What am I doing wrong?

Here's my markup:

```
        $("#acAttendees").jSuggest({
            source: "/api/v1/contacts/SearchContacts",
            selectedItemProp: "Name",
            selectedValuesProp: "ID",
            searchObjProps: "Name",
            queryParam: "SearchText",
            extraParams: "&AssociatesOnly=true",
            selectionClick: function(elem, data) {
                debugger;
            },
            selectionAdded: function(elem, data) {
                debugger;
            },
            selectionRemoved: function(elem, data) {
                debugger;
                elem.remove();
            },
            retrieveComplete: function(data) {
                return data.results; //OData.
            }
        });
```

**Comment by hernantz** [comment]
Hi, i would need to see an example of the server's output. Maybe submiting a jsFiddle could help to see whats going on....

**Comment by JohnGalt1717** [comment]
I hacked around in the source for a while and found that if I set both of those:  
seekVal: "Name",
selectProp: "Name",

it worked properly and looked up. I didn't see either of these in the docs. I have selectedItemProp set to name and selectedValuesProp set to my ID and searchObjProps set to Name as well.

**Comment by hernantz** [comment]
Great :)
