### ISSUE TITLE
selectionClick should pass data as well

### ISSUE THREAD

**Issue by JohnGalt1717** [hernantz/jSuggest#3]
On the selection click I need to get the data that the item is linked to. I can't find it anywhere in the elem that is passed. The event, like selectionAdded and selectionRemoved needs to accept a data parameter with the information.

Thanks! Great control!

**Comment by hernantz** [comment]
I will give it a look this weekend.

**Comment by JohnGalt1717** [comment]
Thanks!

**Comment by hernantz** [comment]
Data should be passed as param in the selectionClicked function on v1.0.2

**Comment by JohnGalt1717** [comment]
Thanks!
