### ISSUE TITLE
When you hit backspace in the text box it fires the selectionClick instead of deleting

### ISSUE THREAD

**Issue by JohnGalt1717** [hernantz/jSuggest#4]
It should delete the item like Apple does when you hit backspace one character after the item.

**Comment by hernantz** [comment]
Do you mean deleting the last item when the input is empty and the user hits backspace? 
If such is the case, it was a design desicion.
Pressing the backspace key will get the expected result. Otherway the user might press accidentally the backspace and delete an item, and by this i mean the cost is hight, becose is not just one letter, a whole word is gone.

**Comment by JohnGalt1717** [comment]
Ok, I just expected it to work like iOS and I would assume most people would...

**Comment by hernantz** [comment]
It shouldn't be difficult to get it, just look at line 184 of jquery.jSuggest.js, it is just an if statement.

**Comment by JohnGalt1717** [comment]
OK, thanks.
