### ISSUE TITLE
Update data source and reset jSuggest.

### ISSUE THREAD

**Issue by idreeshaddad** [hernantz/jSuggest#5]
I want to do something like: every time the user clicks on a button a popup opens, loads data from the server, updates the jSuggest data source, and resets jSuggest input field.

is this possible?

I also noticed that you stopped working on jSuggest, do you suggest another plugin or a widget that could serve me? 

Thank you in advance.

**Comment by hernantz** [comment]
Hi @idreeshaddad,
Sorry for the delay. You should check out http://ivaynberg.github.io/select2/ is more actively maintained and has more features.
